Repository wp-cli/rewrite-command, pull requests merged in 2019-04, with the labels that each got.

#30 Move PHP 5.4 tests from `WP_VERSION` `latest` to `5.1`
  .travis.yml
Labels: scope:distribution

#32 Enhancement: Add PHP 7.3 to Travis CI build matrix
  .travis.yml
Labels: scope:testing

#34 Apply PHPCS `WP_CLI_CS` rules
  .distignore
  .gitignore
  composer.json
  phpcs.xml.dist
  rewrite-command.php
  src/Rewrite_Command.php
Labels: scope:testing

#35 Fix link to config documentation
  src/Rewrite_Command.php
Labels: scope:documentation

#36 Update README.md file
  README.md
Labels: scope:documentation
